# Generated by Django 4.0.6 on 2022-07-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contint', models.CharField(blank=True, max_length=50)),
                ('number_liks', models.IntegerField()),
                ('number_comment', models.IntegerField()),
                ('info', models.CharField(blank=True, max_length=50)),
                ('dateTimeFild', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('password_user', models.CharField(max_length=100)),
                ('dateTimeFild', models.DateTimeField(auto_now=True)),
                ('email_user', models.CharField(blank=True, max_length=100)),
                ('info', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
